name: PatchTST
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.16
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1
  - prompt-toolkit=3.0.51
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.16
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - filelock==3.13.1
      - fonttools==4.58.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - idna==3.10
      - jinja2==3.1.4
      - joblib==1.5.0
      - kiwisolver==1.4.8
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - networkx==3.3
      - numpy==1.26.4
      - packaging==25.0
      - pandas==2.2.3
      - pillow==11.2.1
      - platformdirs==4.3.8
      - protobuf==6.31.0
      - psutil==7.0.0
      - pydantic==2.11.4
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - submitit==1.5.3
      - sympy==1.13.3
      - threadpoolctl==3.6.0
      - torch==2.1.2+cu118
      - torchaudio==2.1.2+cu118
      - torchvision==0.16.2+cu118
      - triton==2.1.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - urllib3==2.4.0
      - wandb==0.19.11
  /pfs/work9/workspace/scratch/ma_skral-SK_thesis_2025/Thesis_MTSF/miniconda3/envs/PatchTST
